name: Ubuntu Workflow

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      crc32:
        required: true
        type: string

jobs:
  tests:
    name: Tests on Ubuntu
    runs-on: ${{ inputs.runner }}
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake gcc libcmocka-dev

      - name: Configure default
        if : ${{ inputs.crc32 != 'arm-crc32' }}
        run: |
          cmake -S . -B build

      - name: Configure with arm crc32
        if: ${{ inputs.crc32 == 'arm-crc32' }}
        run: |
          cmake -DCMAKE_C_FLAGS="-march=armv8-a+crc" -DCMAKE_CXX_FLAGS="-march=armv8-a+crc" -S . -B build

      - name: Build tests
        run: |
          cmake --build build

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure --verbose
